Feature/hw2 custom list
balcon/aston-java-study pull request #1
Opened 2023-11-11 02:49 UTC by balcon

Homework #2
Implementation of custom ArrayList with methods:
 - add(int index, E element)
 - addAll(Collection<? extends E> c)
 - clear()
 - get(int index)
 - isEmpty()
 - remove(int index)
 - remove(Object o)
 - sort(Comparator<? super E> c) - Quick sort

2023-11-11 16:43 UTC, PeterShirin requested changes
1. В методе equals необходимо включить проверку на null.
2. Насколько я знаю, использование inctanceof является не очень хорошим решением на практике. Возможно стоит рассмотреть использование getClass. Например, 
if (obj == null || getClass() != obj.getClass()) {
            return false;
        }
3. Рекомендую избегать использование аннотаций @SupressWarnings("all") и указывать только нужные вам предупреждения.
4. Потенциально в методе hashCode умножение hashcode на число и добавления к нему индекса может привести к коллизиям. Рассмотрите возможность использования более надежного алгоритма для вычисления.

2023-11-11 18:24 UTC, balcon commented
> 1. В методе equals необходимо включить проверку на null.
` obj instanceof CustomList<?>` вернет false если obj будет null. Отдельно проверка на null избыточна.

> 2. Насколько я знаю, использование inctanceof является не очень хорошим решением на практике. Возможно стоит рассмотреть использование getClass. Например,
>    if (obj == null || getClass() != obj.getClass()) {
>    return false;
>    }
Не встречал таких рекомендаций относительно inctanceof, буду благодарен за дополнительную информацию.
В реализации equals библиотечных классов вовсю используется inctanceof. Плюс можно руками не делать приведение типов (с Java 16).

> 3. Рекомендую избегать использование аннотаций @SupressWarnings("all") и указывать только нужные вам предупреждения.
Согласен

> 4. Потенциально в методе hashCode умножение hashcode на число и добавления к нему индекса может привести к коллизиям. Рассмотрите возможность использования более надежного алгоритма для вычисления.
Согласен, следовало воспользоваться готовым `Arrays.hashCode()`

2023-11-11 19:05 UTC, PeterShirin commented
> > 1. В методе equals необходимо включить проверку на null.
> 
> ` obj instanceof CustomList<?>` вернет false если obj будет null. Отдельно проверка на null избыточна.
> 
> > 2. Насколько я знаю, использование inctanceof является не очень хорошим решением на практике. Возможно стоит рассмотреть использование getClass. Например,
> >    if (obj == null || getClass() != obj.getClass()) {
> >    return false;
> >    }
> 
> Не встречал таких рекомендаций относительно inctanceof, буду благодарен за дополнительную информацию. В реализации equals библиотечных классов вовсю используется inctanceof. Плюс можно руками не делать приведение типов (с Java 16).
> 
> > 3. Рекомендую избегать использование аннотаций @SupressWarnings("all") и указывать только нужные вам предупреждения.
> 
> Согласен
> 
> > 4. Потенциально в методе hashCode умножение hashcode на число и добавления к нему индекса может привести к коллизиям. Рассмотрите возможность использования более надежного алгоритма для вычисления.
> 
> Согласен, следовало воспользоваться готовым `Arrays.hashCode()`

Да, согласен, instanceof часто используется в реализации метода equals для обеспечения безопасного сравнения объектов разных типов. Использование instanceof более чем оправдано.

2023-11-12 08:38 UTC, PeterShirin approved these changes

2023-12-12 14:57 UTC, closed without merging